site_name: Minecraft Beginner Portal
theme:
  name: material
  palette:
    primary: black
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
#   - navigation.indexes
    - navigation.toc
#    - navigation.breadcrumb
#    - navigation.footer
#    - navigation.search
#    - navigation.sitemap
plugins: 
  - search
  - glightbox
  - literate-nav:
      nav_file: index.md

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true    
  - admonition
  - md_in_html
  - attr_list
  - abbr
